### ISSUE TITLE
Review del desafío 🕵🏼 

### ISSUE THREAD

**Issue by tobiasfacello** [norbertobaez/norbertobaez.github.io#1]
Buenas tardes Norberto, felicidades por haber llegado al desafío final del módulo 🚀 
Hay un detalle a corregir que me parece importante y es que a partir de cierto ancho de pantalla el layout se rompe en un costado.
Si bien cuando no scrolleas se ve bien, sobrepasa el ancho de la pantalla.
![image](https://user-images.githubusercontent.com/69740939/208750930-a549062a-7e0f-4964-bcb8-67db535039ae.png)

Este error es fácil de solucionar con unidades relativas (que se ve en el próximo módulo) pero con unidades fijas seguro tengas que hacer más media queries para corregirlo y que no afecte al layout general.
Más allá de eso, almenos a mi parecer, cumple con las condiciones para aprobar el desafío. Una vez lo corrijas lo volvemos a revisar, saludos y éxitos!

**Comment by tobiasfacello** [comment]
Otro dato que te puede servir, el problema arranca desde los 800px de ancho en adelante, un par de media queries y lo solucionas 👍🏼

**Comment by norbertobaez** [comment]
hola lo solucione ahi lo vuelvo a subir , me equivoque en un media queries  contenedor-4 habia puesto flex-direction none y era row
